hybrasyl/server

schema.sql
Add a schema to help people trying to do server work without Ealagad.
=> Add schema, temporarily

seed.sql
This adds a seed file to help developers get started running the server locally. @luke-segars
=> Add seed file for adding a few test items, maps, etc

seed.sql
(5,5) is in a countertop. Change to (6,6), which is actually where it should be.
=> Fix default spawn point in seed.sql

hybrasyl/Client.cs, hybrasyl/Objects/User.cs, hybrasyl/QuadTree.cs, hybrasyl/Utility.cs, hybrasyl/World.cs
fix related to SERVER-124 for when a user walks out of a tile after dropping items in the tile
=> Pete bugfix for SERVER-124

hybrasyl/Hybrasyl.csproj, hybrasyl/Objects/Item.cs, hybrasyl/World.cs, hybrasyl/XML/Schema/Items.Designer.cs, hybrasyl/XML/Schema/hybrasylTypes.xsd
This PR addresses SERVER-128, SERVER-68, SERVER-70 and SERVER-71. It adds unique / unique-equipped and master checks, and a slash command `/master` to toggle mastership. It also simplifies item properties.
=> Unique master support

hybrasyl/Objects/User.cs, hybrasyl/Objects/WorldObject.cs, hybrasyl/World.cs
=> GO FORTH AND USE YE SPACEBAR

hybrasyl/Hybrasyl.csproj, hybrasyl/Inventory.cs, hybrasyl/Objects/User.cs, hybrasyl/Objects/WorldObject.cs, hybrasyl/World.cs, hybrasyl/packages.config
=> Inventory is fixed!

hybrasyl/Enums.cs, hybrasyl/FormulaParser.cs, hybrasyl/Hybrasyl.csproj, hybrasyl/Objects/User.cs, hybrasyl/World.cs
=> Basic Attacking, Formula Parsing/Eval, Enum conversion between xsd/enums, assailattack for x13 handler.

hybrasyl/Game.cs, hybrasyl/Objects/Item.cs, hybrasyl/Objects/User.cs, hybrasyl/Packet.cs, hybrasyl/World.cs
* Fix national support, including spawn fixes after timeout
* Require one nation, fail to load world if no nations exist
* Fix two-handed weapon / shield issue (use XSD weapontype enum)
=> 0.5.0 bugfixing

hybrasyl/Objects/User.cs, hybrasyl/Objects/WorldObject.cs, hybrasyl/World.cs
also, rudimentary skill set up.
=> assail fix

README.md, examples/XML/Castable.xml, examples/XML/Item.xml, examples/XML/ItemVariant.xml, examples/XML/Map.xml, examples/XML/Nation.xml, examples/XML/WorldMap.xml
This adds sample XML data that can help answer the question "how do data files work" before we have, you know, actual documentation.
cc: @fluffguck @norrismiv
=> Add example XML data.

hybrasyl/Objects/User.cs
=> [SERVER-173] Implement handling for skills.

examples/XML/castables/Assail.xml, examples/XML/items/Stick.xml, examples/XML/maps/ExampleInn.xml, examples/XML/maps/ExampleVillage.xml, examples/XML/nations/ExampleNation.xml, examples/XML/worldmaps/ExampleWorldMap.xml, hybrasyl/World.cs
This PR cleans up the code to work with the updated XSD Schema definitions.
It also adds new example XML files to work with the updated schemas.
=> Changes for Updated XML Schemas

hybrasyl/Board.cs, hybrasyl/Book.cs, hybrasyl/Client.cs, hybrasyl/FormulaParser.cs, hybrasyl/Hybrasyl.csproj, hybrasyl/Inventory.cs, hybrasyl/Jobs.cs, hybrasyl/Lobby.cs, hybrasyl/Login.cs, hybrasyl/Map.cs, hybrasyl/Monolith.cs, hybrasyl/Objects/ItemObject.cs, hybrasyl/Objects/Monster.cs, hybrasyl/Objects/User.cs, hybrasyl/Objects/VisibleObject.cs, hybrasyl/PlayerStatus.cs, hybrasyl/Server.cs, hybrasyl/ServerPacketStructures.cs, hybrasyl/Utility.cs, hybrasyl/World.cs, hybrasyl/WorldDataStore.cs, hybrasyl/packages.config
This replaces (most) of our overusage of Dictionaries with a new WorldDataStore based on nested `ConcurrentDictionary` objects. It also updates the places we were using those dictionaries. There is still more cleanup to be done but this has been confirmed working.
Also bumps to XML 0.5.5.10.
=> New datastore for stuff in world

hybrasyl/Server.cs, hybrasyl/Utility.cs, hybrasyl/World.cs
=> Thortle fix

hybrasyl/App.config, hybrasyl/Hybrasyl.csproj, hybrasyl/Hybrasyl.sln, hybrasyl/NuGet.config, hybrasyl/Packet.cs, hybrasyl/Properties/Resources.Designer.cs, hybrasyl/Server.cs, hybrasyl/Time.cs, hybrasyl/Utility.cs, hybrasyl/World.cs, hybrasyl/packages.config
=> socket fuckery be gone

hybrasyl/ControlService.cs, hybrasyl/Game.cs, hybrasyl/World.cs
=> Revert "Add in MOTD support"

hybrasyl/Inventory.cs, hybrasyl/Objects/Creature.cs, hybrasyl/Objects/User.cs, hybrasyl/World.cs
-Add healing, and spell casting costs
1) User should be able to heal themselves if damaged
2) User should be able to heal another User / NPC if damaged
3) User should not be able to heal a monster
4) Casting a spell / skill with HP / MP / Gold cost, correctly removed expected HP / MP / Gold from User
5) Casting a spell / skill with Item cost, correctly removed expected Item(s) from User (regardless of Inventory slot)
6) Spell or Skill can not be cast if User does not have sufficient HP / MP / Gold or Item(s) 
-Methods Added: 
---User.cs: canCast, CastingCost, PossibleTargets, and HealTarget
-Methods Modified:
---User.Attack(Castable/Creature), UseSpell, and UseSkill
---Creature.Heal(double/Creature)
---Inventory.SlotOf(string)
=> Update spell casting

HybrasylXML/XSD/Castables.Designer.cs, HybrasylXML/XSD/Castables.xsd, HybrasylXML/XSD/Status.Designer.cs, HybrasylXML/XSD/hybrasylExtensions.cs, HybrasylXML/XSD/hybrasylTypes.xsd, hybrasyl/CreatureStatus.cs, hybrasyl/Enums.cs, hybrasyl/Messaging/ChatCommandHandler.cs, hybrasyl/NumberCruncher.cs, hybrasyl/Objects/ConditionInfo.cs, hybrasyl/Objects/Creature.cs, hybrasyl/Objects/Monster.cs, hybrasyl/Objects/User.cs, hybrasyl/World.cs
- Minor bug fixes to casting: healing should now work, and items costs should be dealt with correctly
- Spell casting (Creature / User)
=> Minor bug fixes to casting

HybrasylXML/XSD/Castables.Designer.cs, HybrasylXML/XSD/Castables.xsd, HybrasylXML/XSD/Status.Designer.cs, HybrasylXML/XSD/Status.xsd, HybrasylXML/XSD/hybrasylExtensions.cs, HybrasylXML/XSD/hybrasylTypes.xsd, README.md, hybrasyl/Client.cs, hybrasyl/CreatureStatus.cs, hybrasyl/Enums.cs, hybrasyl/Game.cs, hybrasyl/Login.cs, hybrasyl/Messaging/ChatCommandHandler.cs, hybrasyl/Messaging/Stats.cs, hybrasyl/Messaging/Statuses.cs, hybrasyl/NumberCruncher.cs, hybrasyl/Objects/ConditionInfo.cs, hybrasyl/Objects/Creature.cs, hybrasyl/Objects/Monster.cs, hybrasyl/Objects/User.cs, hybrasyl/Objects/WorldObject.cs, hybrasyl/Server.cs, hybrasyl/Threading/Lockable.cs, hybrasyl/Utility.cs, hybrasyl/World.cs
Release 0.6.1
#140 #144 #138 #129 #146 #147
=> Hybrasyl 0.6.1

hybrasyl/Hybrasyl.csproj, hybrasyl/NuGet.config, hybrasyl/Scripting/HybrasylDialog.cs, hybrasyl/Scripting/HybrasylDialogSequence.cs, hybrasyl/Scripting/HybrasylMap.cs, hybrasyl/Scripting/HybrasylUser.cs, hybrasyl/Scripting/HybrasylWorld.cs, hybrasyl/Scripting/HybrasylWorldObject.cs, hybrasyl/Scripting/Script.cs, hybrasyl/Scripting/ScriptProcessor.cs
Remove nLua and replace with MoonScript, which is entirely written in C# with no weird DLL dependencies. This replacement is fairly straightforward with not many changes needed.
n/a
Run the server and try to execute lua scripts.
All scripting.
=> initial pass to replace nLua with moonscript

XML/XSD/Castable.xsd, XML/XSD/Objects/Castable.cs, hybrasyl/World.cs
removes usage of `Type` and updates the only usage to be based on `Book` instead
=> remove useless use of Type

hybrasyl/Objects/User.cs
A few sentences describing the overall goals of the pull request's commits.
List related PRs against other branches or any other relevant information.
branch | PR
------ | ------
some_other_PR | [link]()
Outline the steps to test or reproduce the PR here.
List general components of Hybrasyl that this PR will affect:
=> fix class requirements item check, check for learning skills/spells

.gitignore, XML/XSD/Item.xsd, hybrasyl/Compression.cs, hybrasyl/Metafile.cs, hybrasyl/World.cs
in xml,
`<Vendor ShopTab="Scrolls"/>`
or
```
<Vendor ShopTab="Scrolls">
<Description>Returns you to Abel Threshold</Description>
</Vendor>
```
=> enable metafile/vendor tab support

hybrasyl/Scripting/HybrasylUser.cs, hybrasyl/Scripting/Script.cs
Add functions to remove / add gold, as well as retrieve gold, from script objects. Also fix bug in exception logging.
Scripting
=> add Gold/RemoveGold/AddGold; fix scripting logging

hybrasyl/Messaging/Effects.cs, hybrasyl/Objects/User.cs
Implement `/hairstyle <byte style>[<byte color>]` as requested.
Slash commands.
=> implement HYB-16 / #195

hybrasyl/Game.cs, hybrasyl/Legend.cs, hybrasyl/Messaging/Admin.cs, hybrasyl/Messaging/ChatCommandHandler.cs, hybrasyl/Messaging/Legend.cs, hybrasyl/Objects/User.cs, hybrasyl/World.cs
hyb-82: legend fixes; fix potential client crash; clean up quantities 
hyb-78: fix character bouncing against walls/obstacles
=> Legend cleanup and debugging; fix collisions issues

XML/XSD/Extensions.cs, XML/XSD/Objects/Access.cs, XML/XSD/ServerConfig.xsd, hybrasyl/Login.cs, hybrasyl/World.cs
Addresses the last of the 0.7.2 blocker tickets:
hyb-123: make throttling less aggro on dialogs
hyb-132: add reserved name support
List general components of Hybrasyl that this PR will affect:
=> Alpha fixes III: the search for tickets

hybrasyl/Objects/Creature.cs, hybrasyl/Objects/User.cs
=> remove byte that causes full map download on refresh. fix durability divide by zero exception.

hybrasyl/Map.cs, hybrasyl/Objects/Signpost.cs, hybrasyl/World.cs
Fixes a few minor bugs in Boards, now that they're getting exercised.
=> messageboard fixes

hybrasyl/Objects/Creature.cs, hybrasyl/Objects/Monster.cs, hybrasyl/Objects/User.cs, hybrasyl/UserGroup.cs, hybrasyl/World.cs
This fixes:
- Mileth crypt monsters not taking damage
- Invisible monsters 
- Selling items to vendor results in "jazz is like jello pudding" "error" message
- Group XP not working
- Spacebar not working on all monsters
- NPC asks how many items you would like to purchase, but regardless of the number you input, you will only get (and be charged for) one.
- Variants are not vendorable
`Wooden shield not displaying` was fixed previously.
=> alpha day 1 bugfixes

hybrasyl/CreatureStatus.cs, hybrasyl/Objects/Monster.cs, hybrasyl/Objects/User.cs, hybrasyl/Throttle.cs, hybrasyl/World.cs
Address status serialization / spawnpoint null check problems
Ensure creature status ticks end when they do
=> Alpha fixes, part 3

XML/XSD/Map.xsd, XML/XSD/Objects/MapSign.cs, hybrasyl/Board.cs, hybrasyl/Map.cs, hybrasyl/Objects/Signpost.cs, hybrasyl/Objects/User.cs, hybrasyl/Utility.cs, hybrasyl/World.cs
Updates to boards to fix a number of bugs (deletion not working, special characters being replaced with `?` as opposed to 
getting error message, could send empty subject/message, could spam boards and mail, boards didn't work when dead)
Resolves: HS-606, HS-605, HS-604, HS-640, HS-642, HS-641, HS-644, HS-780
=> Updates to boards to fix a number of bugs 

hybrasyl/Map.cs, hybrasyl/Objects/User.cs, hybrasyl/ServerPacketStructures.cs, hybrasyl/World.cs
- fixed purchasing items when your weight exceeds maximum
- fixed user spells displaying the wrong information on the paperdoll
- fixed refreshing to no longer cause the map to fully reload
- fixed doors not refreshing displaying open/closed properly
- fixed hairstyle/color display update to nearby users
- fixed invisible monster bug
=> More Alpha Fixes

hybrasyl/Client.cs, hybrasyl/Login.cs, hybrasyl/Monolith.cs, hybrasyl/Objects/Creature.cs, hybrasyl/Objects/Monster.cs, hybrasyl/Objects/User.cs, hybrasyl/Scripting/HybrasylMap.cs, hybrasyl/Scripting/HybrasylUser.cs, hybrasyl/Server.cs, hybrasyl/Utility.cs, hybrasyl/World.cs
Fixes the following tickets and a number of Sentry exceptions that have been occurring in various places.
HS-806: add Get/SetNation for scripting
HS-805: user deserialization errors should be handled gracefully
HS-804: add null check to lines calculation; trap exceptions
Correct Sentry exceptions: ObjectDisposedError spam; array out of bounds errors in various places; null check in monolith; enumeration changed
=> Moar alpha fixes

hybrasyl/Objects/Creature.cs
This should fix an issue reported by @Caeldeth for things like `beag ioc fein` not working (shapeless intent with group flag)
=> fix group intent, missing NoTarget / Group combo

XML/XSD/Extensions.cs, XML/XSD/Objects/ClientSetting.cs, XML/XSD/Objects/NpcRoleBank.cs, XML/XSD/ServerConfig.xsd, XML/xsd-fix.sh, hybrasyl/Client.cs, hybrasyl/Game.cs, hybrasyl/Inventory.cs, hybrasyl/Messaging/Admin.cs, hybrasyl/Objects/Monster.cs, hybrasyl/Objects/User.cs, hybrasyl/Packet.cs, hybrasyl/World.cs
This PR fully implements client settings, and fixes exchange, making exchange aware of those settings.
It also implements some debug support for the problems we are currently seeing on staging.
=> Settings support

XML/XSD/Castable.xsd, XML/XSD/Extensions.cs, XML/XSD/Objects/CastableEffectsSound.cs, hybrasyl/Book.cs, hybrasyl/ControlMessages/ControlMessage_Spawn.cs, hybrasyl/Inventory.cs, hybrasyl/Objects/Monster.cs, hybrasyl/Objects/User.cs, hybrasyl/Scripting/HybrasylMonster.cs, hybrasyl/Scripting/HybrasylUser.cs, hybrasyl/ServerPacketStructures.cs, hybrasyl/World.cs
- default sound to play 0xFF instead of 0x00
- fix usecount on castables
- fix durability on items
- add new method of tracking threat generation for monsters (including healing)
- fix cancel casting check
=> threat generation, castables, durability, and sound.

hybrasyl/Server.cs
Fix buffer size calculation, which should avoid argument out of range exceptions
=> buffer needs to be sized correctly

XML/XSD/Extensions.cs, hybrasyl/CreatureStatus.cs, hybrasyl/Jobs/StatusTickJob.cs, hybrasyl/Map.cs, hybrasyl/Messaging/Statuses.cs, hybrasyl/Objects/Creature.cs, hybrasyl/Objects/ItemObject.cs, hybrasyl/Objects/User.cs, hybrasyl/World.cs
Fixes the following:
HS-1066: rucesion spawnpoint is in the middle of town (actually worldmap bug)
HS-1026: enable negative hp/mp effects on items
HS-611: skulling does not work when grouped
HS-878: statuses do not appear to clear properly
Also: add privileged chat using @ as whisper target
=> Alpha fixes phase3

hybrasyl/ControlMessages/ControlMessage_Spawn.cs, hybrasyl/Objects/ItemObject.cs, hybrasyl/Objects/Monster.cs, hybrasyl/Objects/User.cs, hybrasyl/World.cs
Fixes:
HS-728: equipping armor doesn't show stat changes
HS-761: confusion occurring when trying to equip items over equip weight limit
HS-764: allow other items or gold to be picked up under items or gold that cannot be picked up
HS-1091: monsters should be impacted by sleep/freeze/paralyze
HS-972: exchange must be toggled on/off for new characters
HS-828: can't learn a spell with exactly the right amount of gold
=> Alpha phase 3 part mcmclxviii fixes

hybrasyl/Objects/User.cs
handles special cases for weapon type and armor type for monk/warrior, as they have unique cases, otherwise defaults to 1.
=> add in special assailattack motion handling

hybrasyl/Manufacture.cs, hybrasyl/Objects/User.cs, hybrasyl/World.cs
Implements baseline manufacturing mechanic using manufacturing UI. Supports creating an item (based on recipe name) with required ingredients list.
=> Manufacturing

hybrasyl/Objects/User.cs, hybrasyl/ServerPacketStructures.cs, hybrasyl/UserGroup.cs, hybrasyl/World.cs
Fully implements group recruiting mechanic (AKA "group box"). Group leader (or ungrouped user) can fill in recruitment info in group window (Y key), allowing other users who meet qualifications to join the leader's group at will.
=> Group Recruiting

hybrasyl/Objects/User.cs, hybrasyl/Objects/VisibleObject.cs, hybrasyl/Utility.cs, hybrasyl/World.cs
Fixes the issues addressed in the commit messages.
=> Bug fix extravaganza

hybrasyl/Objects/Signpost.cs
From 3000 to 6000
A few sentences describing the overall goals of the pull request's commits.
List related PRs against other branches or any other relevant information.
branch | PR
------ | ------
some_other_PR | [link]()
Outline the steps to test or reproduce the PR here.
List general components of Hybrasyl that this PR will affect:
=> Double AOIEntry Delay Effect

hybrasyl/Packet.cs
Yeah, I'm not filling out a form to submit code changes for one file. Thanks though.
Behavior of the new code is different, and that's good because the old code was wrong. The logic for which packets use which encryption was taken straight from the client disassembly, which in turn was cross checked against my own private server code that uses the same logic.
=> Simplify code in Packet.cs
