hybrasyl/server

- seed.sql
This extends seed.sql to include the minimum viable amount of information currently required to make Hybrasyl loggable. I just tested in from an empty database and combined with schema.sql all seems to work well.
One potential issue: I have to create a default nation called "Mileth" because DEFAULT_CITIZENSHIP is set to "Mileth" in the code, and it therefore expects a nation called Mileth to exist. @baughj, is it preferable to include this nation, or to change the default to something else?
> Added missing SQL data required to make Hybrasyl loggable.

- hybrasyl/Inventory.cs
- hybrasyl/Objects/Item.cs
- hybrasyl/Objects/User.cs
See bug at https://hybrasyl.atlassian.net/browse/SERVER-69 and #6, a past pull request (obsolete).
This patch modifies how inventory weight is stored to support negative weights. Mark's diagnosis in the bug was correct; previously weight was being stored as an unsigned integer (meaning no negatives and it'd wrap around to a gigantic value if you tried).
Not a lot of notable changes here, but one explicit design decision work mentioning. I separated Inventory.CurrentWeight into two different properties: CurrentWeight (the true weight of the inventory, which could be negative), and VisibleWeight (which is never less than zero, intended to be displayed to the client). This introduces potential for bugs down the road since there are two ways to access the weight, though IMO this is the …
> Supporting negative weights, take two

- hybrasyl/Hybrasyl.csproj
- hybrasyl/Objects/User.cs
- hybrasyl/UserGroup.cs
- hybrasyl/Utility.cs
- hybrasyl/World.cs
This is a pretty big one so I've broken it up into three revisions for review. Happy to collapse them later.
A general overview of the design is here: https://docs.google.com/document/d/1aIjHNzWSw3Y1Zm3ndEjmkV4yjL2hUlxaQJo_aGI_dgE/edit#. Note that I wrote this up beforehand so there may be some slight discrepancies.
This PR introduces the UserGroup class, which represents groups of users that can communicate together (via group whisper) and share resources (such as experience). A few things to note:
- This introduces support for two opcodes: **0x2E** (called GroupRequest) and **0x2F** (called GroupToggle).
- Group joining / leaving interactions have been kept as similar as I could to what USDA does, with the exception of some messaging. Certain messages are changed to strings that are …
> Support for grouping

- hybrasyl/Objects/Item.cs
fix server logic to prevent equipping two-handed sword with a shield,
and vice versa
> bugfix SERVER-122 two handed weapon and shields

- hybrasyl/Game.cs
- hybrasyl/Hybrasyl.csproj
- hybrasyl/Objects/User.cs
- hybrasyl/Time.cs
- hybrasyl/Utility.cs
- hybrasyl/World.cs
This PR adds support for "Aisling" time, which can have fairly sophisticated definitions in the server configuration XML. A server can have `Ages`, defined with start and end dates, along with an age name and a start year (e.g. "Hybrasyl 5" or "Chadul 66"). There is also support for a simple default age ("Hybrasyl") with a default year (1).
By default, the server, on first startup, will save the start time as the canonical start date for Aisling timekeeping. This time can be reset later but may have unexpected effects, as legend marks et al will not store Aisling time, but `DateTime` objects (meaning the legend mark dates may shift or be completely nonsensical if the start date is changed later).
This PR also adds the slashcommands `/time` and `/timeconvert` to test the functionality. …
> [SERVER-172] Implement support for Aisling time

- CHANGELOG.md
- hybrasyl/Enums.cs
- hybrasyl/Hybrasyl.csproj
- hybrasyl/Legend.cs
- hybrasyl/Objects/User.cs
- hybrasyl/Time.cs
- hybrasyl/World.cs
This PR extends the legend mark support to use a new container `Legend` which supports enumeration and also exposes a public API that can be used by scripting. Legend marks have a `ToString` override that builds a display string based on whether or not a mark is public (private appends ` - ` to a mark and will only display to the user with the mark), quantity (e.g. `Herp Derp (38) - Hybrasyl 1, Winter`), and date. The date can be any date that Hybrasyl knows about via the time configuration (so marks can extend across a number of defined ages). Legend mark dates are stored as Terran dates and converted to Aisling dates when needed.
Prefixes are essentially string keys that can be used to identify legend marks later; their function from commercial is carried over here. A separate index is …
> [server-170] Implement legend mark support

- hybrasyl/Objects/User.cs
- hybrasyl/World.cs
This fixes a bug where we are not properly recalculating things like AC/MR/etc at login because deserializing Equipment doesn't result in bonuses / etc being applied. 
A better long term fix for this is to handle it in the deserializer itself but this will do for now.
cc: @norrismiv
> Ensure item bonuses are recalculated on login (resolves #42)

- hybrasyl/Objects/Item.cs
- hybrasyl/Objects/User.cs
- hybrasyl/Objects/WorldObject.cs
- hybrasyl/Scripting.cs
- hybrasyl/Utility.cs
- hybrasyl/World.cs
This PR implements use support for items. Items can have the following effects, any of which can be combined (and are specified via the item XML):
* arbitary Python scripts
* animation effects
* sound effects
* simple player effects (+/- hp,mp,xp,gold)
* teleportation
This PR also implements a generic `Heal` function, similar to `Damage`, and provides an override for `User` to properly update the client and/or display healthbars after heal/damage occurs. It also implements a new `HealToFull` script API function, health/damage/teleport API functions for scripts, and a new `common` directory for shared effect scripts (such as "reduce HP to 1" or "heal to full HP", etc).
> [SERVER-85] Implement use support on items

- hybrasyl/Objects/User.cs
- hybrasyl/Utility.cs
- hybrasyl/World.cs
This PR updates levelling to ensure that experience cannot overflow, that levels should only go upwards, and that you cannot exceed `Constants.MAX_LEVEL` for your level. Your "XP to next level" will correctly display as 0 at `MAX_LEVEL` and experience will be properly added to your box in all cases.
It also adds a slash command `/expreset` for testing.
cc: @norrismiv
> [SERVER-158] Fix level / experience overflows

- hybrasyl/Legend.cs
- hybrasyl/Objects/User.cs
- hybrasyl/Objects/WorldObject.cs
- hybrasyl/Scripting.cs
This PR adds Python API support for legend marks: `GetLegend`, `GetLegendMark`, `RemoveLegendMark`, and `ModifyLegendMark`. These can be used by NPCs or other scripts to modify a player's legend.
Also included: refactoring to scripting / script handlers to allow `/scripting reload riona.py` to work as expected, renaming `String` to `string`, and fixing a formatting bug when time since last login is displayed to the user.
cc: @norrismiv
> [SERVER-171] Add Python API support for legend marks

- hybrasyl/Enums.cs
- hybrasyl/Inventory.cs
- hybrasyl/Objects/User.cs
- hybrasyl/ServerPacketStructures.cs
This PR is a very simple fix - exchanges will now display quantity in the exchange window for a stackable item (e.g. `Moldy Newspapers (3)`).
> [SERVER-159] Display item quantities in exchange window

- README.md
- examples/XML/maps/ExampleVillage.xml
The server is crashing without this. Otherwise setup has been a breeze so far.
Update: also corrected the URL to the new launcher in the README. Current one is broken.
I agree to the terms of the Contributor Agreement outlined at https://github.com/hybrasyl/server/blob/master/CONTRIBUTING.md.
> Adds a missing XML tag into ExampleVillage.xml

- hybrasyl/Objects/WorldObject.cs
- hybrasyl/Utility.cs
Clamps the upper and lower bounds for a bunch of different `Creature` stats. The bounds currently in place are specified here: https://hybrasyl.atlassian.net/browse/SERVER-84.
| Stat | Min | Max |
| ----- | ----- | ----- |
| STR | 1 | 255 |
| INT | 1 | 255 |
| WIS | 1 | 255 |
| CON | 1 | 255 |
| DEX | 1 | 255 |
| HIT | 0 | n/a |
| DAM | 0 | n/a |
| MR | 0 | 8 |
| AC | -90 | 100 |
| HP | 1 | n/a |
| MP | 1 | n/a |
True (unclamped) values are still being preserved in the Creature object so adding and removing inventory items *should* work (and does in the testing I did locally). Any suggestions?
Note that this doesn't fix the lower limit for experience mentioned in the bug report; there's no auto prop for experience so I'm gonna have to test that a bit more thoroughly. Can follow up with …
> [SERVER-84] Inadequate stat limits

- hybrasyl/World.cs
Doesn't display this message if the user has never logged off, i.e. if they're a first-time user. Fixes #49.
Note that USDA still does display the message "0 hours and 0 minutes have passed since you last logged in", but I'd argue its better to just not say anything. Their message doesn't make much sense.
> Condition 'last login' message on whether they've logged in before

- hybrasyl/Book.cs
- hybrasyl/Enums.cs
- hybrasyl/Hybrasyl.csproj
- hybrasyl/Inventory.cs
- hybrasyl/Jobs.cs
- hybrasyl/Legend.cs
- hybrasyl/Map.cs
- hybrasyl/Objects/ItemObject.cs
- hybrasyl/Objects/Merchant.cs
- hybrasyl/Objects/User.cs
- hybrasyl/Objects/WorldObject.cs
- hybrasyl/Packet.cs
- hybrasyl/PlayerStatus.cs
- hybrasyl/Scripting.cs
- hybrasyl/Server.cs
- hybrasyl/ServerPacketStructures.cs
- hybrasyl/Time.cs
- hybrasyl/UserGroup.cs
- hybrasyl/Utility.cs
- hybrasyl/World.cs
This PR adds status support: poison, sleep, blind, death, etc. It also adds a number of new enums and support for display packet in the new structure format. Cooldown support and status ticks are also added.
> [server-167] Add status support

- README.md
Update README to indicate SDK is no longer a thing, at least for server.
> Update README.md (#100)

- hybrasyl/Compression.cs
This adds the missing checksum to the end of zlib-compressed streams, which should fix the notification window at the login screen not updating as well as the client ignoring metafiles.
> Fix incomplete zlib compression

- hybrasyl/Dialogs.cs
- hybrasyl/Scripting/HybrasylDialogSequence.cs
- hybrasyl/World.cs
This PR fixes the issue where clicking `next` from a dialog will not advance back to the main menu.
n/a
Talk to an NPC, open a dialog sequence; click next through it - ensure that at the end of the sequence, hitting next returns to the main menu.
Dialogs.
> [SERVER-226] Can't click Next and go to top level menu

- hybrasyl/Client.cs
- hybrasyl/Game.cs
- hybrasyl/Server.cs
This PR updates sending and receiving in Hybrasyl to be completely asynchronous, and removes any legacy packet processing code we had from when Hybrasyl was still single threaded. Sending and receiving now follow the same pattern, as well, and most functionality has been moved into `Client` / `ClientState`.
@norrismiv and I consider this to be a fix to the "socket problems"; testing under load will demonstrate that this is a definitive fix.
None.
Make lots of bees. Note that the bees (and the packets they generate) do not crash the server or client or result in strange disconnects.
Network receive / send.
> Remove SendLoop once and for all

- examples/XML/items/Stick.xml
- examples/XML/itemvariants/Elemental.xml
- examples/XML/maps/ExampleInn.xml
- examples/XML/maps/ExampleVillage.xml
- examples/XML/npcs/ExampleBeggar.xml
- examples/XML/npcs/ExampleInnKeeper.xml
Some of the XML elements / attributes have changed, so the Example XML files are currently showing errors in the server logs. These corrections update the XML files to remove these errors from occurring.
Update to items/Stick, itemvariants/Elemental, maps/ExampleVillage, and maps/ExampleInn. 
Added npcs/ExampleInnKeeper and npcs/ExampleBeggar.
- Replace XML files, run server. No errors should be indicated.
- Login with a character, ExampleInn has an Inn Keeper showing.
- Example contents
> Update Sample XMLs

- hybrasyl/Game.cs
- hybrasyl/Objects/User.cs
- hybrasyl/Server.cs
- hybrasyl/World.cs
This PR fixes #138 and ensures that an orderly shutdown occurs (with no unhandled exceptions / etc) when the server is shut down using the REST control service.
n/a
User list: 
1) Log on more than once.
2) Confirm that who list shows correct number of users.
3) Log one user off.
4) Confirm who list does not show the logged off user.
Shutdown: 
1) Use the ControlService to shutdown the server. 
Powershell command that can be used to test this:
`Invoke-RestMethod -Uri http://127.0.0.1:4949/ControlService/Shutdown/<shutdownpassword>`
2) The server should shut down (all users get "Chaos is rising up" followed by disconnects)
3) You should get a successful response from `Invoke-RestMethod`
4) server should close (exit) without incident (e.g. no unhandled exceptions or crashing).
Finally using …
> Fix #138: use active users for who list / ensure shutdown works correctly

- hybrasyl/Objects/User.cs
Fix a bug where we weren't sending the correct equipment packets on re-login. Specifically for rings, this was causing an issue where we were sending incorrect item slots, resulting in a ring appearing as a stave and no rings showing up.
n/a
1. Equip a full slate of equipment. Confirm that it all displays correctly.
2. Logoff.
3. Log back in and verify that the equipment was not only correctly re-equipped, but also displays correctly in your profile screen.
Login only, this is the result of an edge case rather than a general equipment / inventory display bug
> Ensure we redisplay equipment correctly on login (#129)

- HybrasylXML/XSD/hybrasylConfig.Designer.cs
- HybrasylXML/XSD/hybrasylConfig.xsd
- HybrasylXML/XSD/hybrasylExtensions.cs
- hybrasyl/Board.cs
- hybrasyl/Dialogs.cs
- hybrasyl/Legend.cs
- hybrasyl/Login.cs
- hybrasyl/Map.cs
- hybrasyl/Messaging/Admin.cs
- hybrasyl/Objects/Merchant.cs
- hybrasyl/Objects/User.cs
- hybrasyl/Objects/WorldObject.cs
- hybrasyl/Scripting/HybrasylDialog.cs
- hybrasyl/Scripting/HybrasylUser.cs
- hybrasyl/Scripting/HybrasylWorld.cs
- hybrasyl/Scripting/HybrasylWorldObject.cs
- hybrasyl/Scripting/Script.cs
- hybrasyl/Scripting/ScriptProcessor.cs
- hybrasyl/Time.cs
- hybrasyl/Utility.cs
- hybrasyl/World.cs
PR adding functionality related to Mileth scripting
n/a
Use `mileth-scripting` branch from `world`, note that Riona works completely
* Adds `/reloadnpc` command, can be used to reload NPC scripts
* Adds `/showcookies`, `/deletecookies`, `/deletesessioncookies` commands (cookies are small fragments of session-based or permanent data that can be used by scripts to set state)
* Implements handling of Lua callbacks for text/option dialogs
* Implements `FunctionDialog`, a type of dialog that can be used to run independent Lua code in between two displayed dialogs, and `JumpDialog`, a dialog that will jump to another registered dialog or dialog sequence
* Extend time handling and simplify implementation; verify multiple ages (Danaan / Deoch) work as expected
* Implement additional Lua …
> Mileth scripting

- XML/XSD/hybrasylExtensions.cs
- hybrasyl/Inventory.cs
- hybrasyl/Map.cs
- hybrasyl/Monolith.cs
- hybrasyl/Objects/Creature.cs
- hybrasyl/Objects/ItemObject.cs
- hybrasyl/Objects/User.cs
- hybrasyl/Scripting/HybrasylUser.cs
- hybrasyl/Scripting/ScriptProcessor.cs
- hybrasyl/Utility.cs
- hybrasyl/World.cs
- hybrasyl/WorldDataStore.cs
This PR fixes a number of issues exposed by reusing global scripts / dialogs, and Mileth scripting more generally. The usage of shared global dialogs and reactor script reuse now works as expected.
n/a
1. Login
2. Use current world repo
3. Note that "wakeup scripts" work
4. Go downstairs
5. Note that all paths of Riona greeting work
* `WorldDataStore` indexes and keys are now normalized: `ToLower()` and all whitespace removed.
* Script names are now normalized in a similar fashion (and `.lua` is removed).
* Items now use a short-SHA hash as an ID. No more of this weird unsigned / unchecked int shit.
* Bug with global dialog sequences not working fixed. They are now stored at the top (65535 and downwards) of the sequence space, rather than the bottom.
* Bug with shared sequences fixed by …
> Scripting updates & fixes roundup - August 2019

- hybrasyl/Dialogs.cs
- hybrasyl/Inventory.cs
- hybrasyl/Messaging/Admin.cs
- hybrasyl/Objects/WorldObject.cs
- hybrasyl/Scripting/HybrasylDialogSequence.cs
- hybrasyl/Scripting/HybrasylUser.cs
- hybrasyl/Scripting/HybrasylUtility.cs
- hybrasyl/Scripting/HybrasylWorld.cs
- hybrasyl/Scripting/HybrasylWorldObject.cs
- hybrasyl/Scripting/Script.cs
- hybrasyl/World.cs
- hybrasyl/WorldDataStore.cs
* Add convenience functions for dialog generation (`NewTextAndJumpDialog`, `NewSimpleDialogSequence`, `NewEndDialog`)
`NewSimpleDialogSequence` takes a list of strings and generates a dialog sequence consisting of the text passed to it. For instance:
`NewSimpleDialogSequence("foobar", "a", "b", "c", "d")` would create a `DialogSequence` named "foobar" with four dialogs a->b->c->d.
`NewTextAndJumpDialog` creates a sequence that displays one dialog and then jumps to something else. This is a convenience function that actually creates an anonymous sequence consisting of a `SimpleDialog` and a `JumpDialog`. You can use this to either jump to an arbitrary sequence, or, `MainMenu`, which will display the main menu.
`NewEndDialog` creates a dialog that displays one reply and then "ends". This is …
> Scripting API / dialog updates

- XML/XSD/Objects/LocalizedString.cs
- XML/XSD/Objects/ServerConfig.cs
- XML/XSD/ServerConfig.xsd
- hybrasyl/Connection.cs
- hybrasyl/Game.cs
- hybrasyl/Server.cs
- hybrasyl/World.cs
This PR cleans up packet queues & exit handlers to function more cleanly (address some null references), adds `<Motd>` to XML support to replace the control service functionality; handles errors better for missing directories / etc.
The config file generator is removed; if a config file is not found a user will be told to visit the community database for an example `config.xml`.
Lastly the missing spell handlers for forgetting a spell were added.
> Cleanup packet queue, exit handlers, config file handling

- .gitignore
- hybrasyl/Client.cs
- hybrasyl/Map.cs
- hybrasyl/Messaging/Debug.cs
- hybrasyl/Monolith.cs
- hybrasyl/Objects/Monster.cs
- hybrasyl/World.cs
- hybrasyl/WorldDataStore.cs
This PR fixes several bugs in looting / mob death based on testing.
* Fix several bugs in loot calculations
* Fix null reference exceptions in loot calculations / mob death
* Optimize monster spawn calculations, increase mob responsiveness
* Fix bug where low-powered variance would cause unhandled exceptions
* Ensure item variants specified in loot drop and serialize correctly
List general components of Hybrasyl that this PR will affect:
Looting
Mob death (with looting)
> Loot testing fixes

- hybrasyl/Time.cs
Fix bug in time handling (there is no 0th moon or 0th sun)
Legend marks that are applied in "moon zero" now correctly display as `Winter`, as it is actually moon 1
Time will never display Moon 0 / Sun 0
> Refine handling of moon/sun in time

- hybrasyl/World.cs
This fixes a bug where only stackable items are inserted back into the world when dropped, which is necessary in order to assign them an ID. Later, when the item is picked back up, the server sends a remove packet with this ID; for non-stackable items this ID was being set to `0` rather than the correct value.
Repeat steps in #178, note that it is fixed.
Item drop packet handler
> fix display issue where picked up items don't vanish on client side

- hybrasyl/Objects/Creature.cs
- hybrasyl/Scripting/HybrasylUser.cs
- hybrasyl/Scripting/Script.cs
Check to see if someone is alive before resurrecting them. Also add `Alive` as a boolean field to `HybrasylUser` for scripts and `SendHome` to send a player back to their spawnpoint.
> add Alive / SendHome; don't resurrect alive people

- .gitignore
- XML/XML.csproj
- hybrasyl/Book.cs
- hybrasyl/FormulaParser.cs
- hybrasyl/Hybrasyl.csproj
- hybrasyl/Inventory.cs
- hybrasyl/Legend.cs
- hybrasyl/Objects/Creature.cs
- hybrasyl/Objects/User.cs
- hybrasyl/Objects/VisibleObject.cs
- hybrasyl/Scripting/HybrasylUser.cs
- hybrasyl/Scripting/Script.cs
- hybrasyl/Scripting/ScriptProcessor.cs
- hybrasyl/Utility.cs
- hybrasyl/World.cs
HYB-64: bugfixing
HYB-82: correct requirement for legend marks to have prefixes
HYB-18: /legend now allows dates / quantities to be properly set for testing, and doesn't make it so you can't login 😄 
HYB-36 / #145 - correctly handle primary/secondary/utility skills in panes
HYB-79: perform null checks for formula parser tokens that may be null
**Other**
Add slight-REPL loop for scripting usage, using whisper target $
Fix error in intent calculations: monsters should always be healable / statusable
Fix crash error in `e` (who list)
Fix null check error in weapon durability
> Scripting fixes; fix bugs; add REPL scripting loop 

- hybrasyl/Dialogs.cs
- hybrasyl/FormulaParser.cs
- hybrasyl/Map.cs
- hybrasyl/Messaging/Admin.cs
- hybrasyl/Scripting/HybrasylUser.cs
- hybrasyl/Scripting/HybrasylWorld.cs
- hybrasyl/World.cs
This PR fixes a number of bugs identified by @SmashleyMcNerdface while doing Mileth scripting. It also provides a few enhancements.
* Allow JumpDialogs to specify Lua callbacks via scripting, and ense they are run.
* Update /teleport to take NPC name or map name.
* Add FindEmptyTile to Map for scripting / command usage.
* Add CompletionAward to be used in scripting for simple check-if-user-has-done-this-if-not-give-xp steps (Graymayre, et al)
Observe that `NewTextAndJumpDialogs` are not duplicated (before, Menu->Select A->B->C->Menu was being rendered as Menu->Select A->B->B->C->Menu).
Scripting / dialogs
> Dialog bug squashing, teleport updates, fixes

- hybrasyl/Client.cs
- hybrasyl/Enums.cs
- hybrasyl/Map.cs
- hybrasyl/Objects/User.cs
- hybrasyl/Packet.cs
- hybrasyl/Server.cs
When async outbound delivery of packets was introduced, it created a race condition where packets can be received out of order by the client. This had a number of knockoff effects where packets need to be received in order (such as picking an item up off the ground, etc).
This PR introduces the concept of a server thread that runs asynchronously to deliver packets. The `Enqueue` is changed to only enqueue packets into the concurrent queue; the server thread is responsible for delivery. Currently, this thread runs asynchronously every 50ms.
This is a suggestion for how to fix it - I am more than happy to get feedback and suggestions.
In particular, test map renders correctly (GM Test Area) and the issues noticed in HYB-94 are resolved (picking an item up over your weight results in item …
> refactor async packet delivery

- XML/XSD/Common.xsd
- XML/XSD/Item.xsd
- XML/XSD/Objects/Item.cs
- XML/XSD/Objects/ItemFlags.cs
- hybrasyl/Game.cs
- hybrasyl/Map.cs
- hybrasyl/Objects/ItemObject.cs
- hybrasyl/Objects/Monster.cs
- hybrasyl/Scripting/HybrasylDialog.cs
- hybrasyl/Scripting/HybrasylDialogSequence.cs
- hybrasyl/Scripting/HybrasylUser.cs
- hybrasyl/Scripting/HybrasylUtility.cs
- hybrasyl/Scripting/HybrasylWorld.cs
- hybrasyl/Scripting/HybrasylWorldObject.cs
- hybrasyl/Scripting/Script.cs
- hybrasyl/Time.cs
- hybrasyl/World.cs
Significant refactoring to scripting logging, improve error reporting - Lua will now give detailed reports about startup / execution errors, which should help with scripting work and general debugging. The lines around the error in the script are printed, and the line itself where the error happened is indicated with an arrow:
Runtime error example:
```
2020-08-13 10:57:32.961 -07:00 [ERR] ExecuteFunction: Error executing function OnSpawn in Cian.lua (associate Cian):
Scripting runtime error: Line 73: cannot access field StoreEphemeral of userdata<Hybrasyl.Scripting.HybrasylWorldObject>
```
Syntax error example:
```
2020-08-13 10:57:31.931 -07:00 [ERR] Run: Error executing script TrainingDummy.lua (associate none):
Syntax error: Line 18: unexpected symbol near 'then'
```
Add startup check …
> Improvements to error reporting 

- hybrasyl/Game.cs
- hybrasyl/Hybrasyl.csproj
- hybrasyl/Messaging/Info.cs
This fixes an occasional problem with builds caused by our attempt to embed the last commit log from HEAD into the build for the purposes of showing it to the user in motd and via `/version`. This cleans that up, and uses an async to fetch commit information from GitHub on server startup instead.
> Clean up build process / version information retrieval

- hybrasyl/Objects/Merchant.cs
- hybrasyl/Objects/Monster.cs
- hybrasyl/Objects/VisibleObject.cs
- hybrasyl/Scripting/Script.cs
This PR adds `OnHear` as a scriptable handler as requested by @smashleymcnerdface for handling marriage. `VisibleObjects` can define this handler to react to speech from either another NPC or player.
For example, in a Lua script:
```lua
function OnHear()
if (shout) then
associate.Say("You don't have to yell, " .. invoker.Name);
else
associate.Say("I heard that!");
end
end
```
see https://streamable.com/m471kr for video of above example
Add an `OnHear` handler to a NPC or creature script.
Say something to them.
n/a, new functionality, there is a slight change to how speech is processed
> Add OnHear handler to allow NPC/creatures to react to speech

- XML/XML.csproj
- XML/XSD/Extensions.cs
- XML/XSD/Objects/ApiEndpoints.cs
- XML/XSD/ServerConfig.xsd
- hybrasyl/Board.cs
- hybrasyl/Client.cs
- hybrasyl/Connection.cs
- hybrasyl/CreatureStatus.cs
- hybrasyl/Dialogs.cs
- hybrasyl/Game.cs
- hybrasyl/Hybrasyl.csproj
- hybrasyl/Jobs.cs
- hybrasyl/Messaging/Admin.cs
- hybrasyl/Messaging/Debug.cs
- hybrasyl/Messaging/Effects.cs
- hybrasyl/Messaging/Info.cs
- hybrasyl/Messaging/Legend.cs
- hybrasyl/Messaging/Stats.cs
- hybrasyl/Messaging/Statuses.cs
- hybrasyl/Monolith.cs
- hybrasyl/NumberCruncher.cs
- hybrasyl/Objects/Merchant.cs
- hybrasyl/Objects/Monster.cs
- hybrasyl/Objects/User.cs
- hybrasyl/Packet.cs
- hybrasyl/Scripting/HybrasylUser.cs
- hybrasyl/Scripting/HybrasylUtility.cs
- hybrasyl/Scripting/Script.cs
- hybrasyl/Server.cs
- hybrasyl/World.cs
This PR adds Sentry for error reporting in most places (and all unhandled exceptions). It also simplifies access checks for privileged uses and adds support for a wildcard (e.g. `*`) to make local testing easier.
Also corrects a few bugs in the new `OnHear` handler for mundanes.
Lastly, most slash commands are now defaulted to requiring privilege as we get closer to alpha.
Privileged user checks
All exception handling
> Add Sentry for error reporting; simplify access checks; fix OnHear bugs

- hybrasyl/Client.cs
- hybrasyl/CreatureStatus.cs
- hybrasyl/Jobs.cs
- hybrasyl/Login.cs
- hybrasyl/Messaging/Admin.cs
- hybrasyl/Messaging/Effects.cs
- hybrasyl/Objects/Creature.cs
- hybrasyl/Objects/User.cs
- hybrasyl/Objects/VisibleObject.cs
- hybrasyl/World.cs
- hybrasyl/WorldDataStore.cs
This PR cleans up our storage and usage of logged in users. There were a couple of bugs / unintended consequences:
1) `WorldData.Remove` was not sanitizing the key, which means was not lowercased; so if you were logged in as Science, remove was attempting to remove the key "science". This means the user object would persist after logout in a particularly interesting state (client disconnected, but still in world). I believe this wasn't helping re: the "ghost" issue.
2) `WorldData<User>` was being used to store user objects but partially because of above, would eventually diverge from the contents of the `ActiveUsers` concurrent dictionary. `ActiveUsers` is basically tech debt at this point and has been removed. Any usage of it has been cleaned up. `ActiveUsers` property can still be …
> Clean up storage of logged in users / fix worlddatastore bugs

- hybrasyl/Client.cs
- hybrasyl/Enums.cs
- hybrasyl/GameLog.cs
- hybrasyl/Packet.cs
- hybrasyl/Server.cs
- hybrasyl/World.cs
This PR fixes a packet processing issue that was only happening on fragmented packets (eg over Internet, > 1460 bytes). This updates the buffer to be correctly length checked and continually read into when the initial async read does not completely finish reading the entire packet off the socket.
Literally all packet processing.
> Fix packet processing issue

- hybrasyl/Objects/Creature.cs
- hybrasyl/Objects/Monster.cs
- hybrasyl/Objects/User.cs
- hybrasyl/World.cs
Don't allow further damage to be done to a mob at 0 hp
checks to not run ondeath twice (alive cannot be used for this purpose as alive has a different semantic meaning for users, since users have both alive/coma)
> OnDeath fixes

- hybrasyl/Monolith.cs
Fix concurrency issue with monolith thread; catch exceptions which were previously crashing the entire server
> handle exceptions in monolith; use local map list with 15 second refresh

- hybrasyl/Map.cs
- hybrasyl/Messaging/Stats.cs
- hybrasyl/Objects/Merchant.cs
- hybrasyl/Objects/User.cs
- hybrasyl/World.cs
This fixes the following:
HS-1020: Handle NPC errors gracefully, don't cause map outages
HS-1022: item variants could be created with levels over 99
HS-1021: NPCs should check both skill/spell prerequisites for learning
> Alpha fixes phase3

- hybrasyl/ControlMessages/ControlMessage_Spawn.cs
- hybrasyl/Monolith.cs
- hybrasyl/Objects/Monster.cs
While this does not remove the need for controlmessages entirely, this does reduce the number of control messages processed by offloading the work to the monster object itself and limiting the monsters being processed to only those who have a user in their active viewport.
> Mob processing update
